name: docker push 

on:
    push:
        branches:
            - master 

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
            uses: actions/checkout@v2
            with:
                ref: master
            
            - name: Build and push Docker image 
            uses: docker/build-push-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: sjha2048/parse_dokku
                tags: latest 
